src/Portal/Controllers/UserManagementController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.WhiteSpaces.Portal.Controllers
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Microsoft.Practices.Unity;
    using Microsoft.Whitespace.Common;
    using Microsoft.WhiteSpaces.AzureOAuthProvider;
    using Microsoft.WhiteSpaces.AzureTableAccess;
    using Microsoft.WhiteSpaces.BusinessManager;
    using Microsoft.WhiteSpaces.Common;
    using Microsoft.WhiteSpaces.Common.Enums;

    public class UserManagementController : Controller
    {
        private const int PageSize = 10;
        private static object lockObject = new object();  
        private readonly IUserAdminManager adminManager;
        private readonly IWhitespacesManager whitespacesManager;              

        public UserManagementController(IUserAdminManager userManager, IWhitespacesManager whitespacesManager)
        {
            this.adminManager = userManager;
            this.whitespacesManager = whitespacesManager;
        }

        [Dependency]
        public IAuditor UserManagementAuditor { get; set; }

        [Dependency]
        public ILogger UserManagementLogger { get; set; }        

        // GET: /UserManagement/
        public ActionResult Index()
        {
            return this.View();
        }

        public PartialViewResult GetAllUsersInfo()
        {
            IEnumerable<UserInfo> users = this.adminManager.GetAllUsersInfo();
            return this.PartialView("UsersPartial", users);

            // IEnumerable<IntialUserInfo> userList = this.adminManager.GetIntialUserList(null);
            // return PartialView("UsersPartial", userList);
        }

        public PartialViewResult LoadUserInfo()
        {
            IEnumerable<IntialUserInfo> userList = this.adminManager.GetIntialUserList(null);
            UserSearchViewModel model = new UserSearchViewModel();
            userList = userList.OrderBy(x => x.UserName);
            var pagedUserlist = userList.Skip(0).Take(PageSize);
            ViewBag.rowCount = userList.Count();
            ViewBag.pageIndex = 0;

            model.UserList = pagedUserlist;
            model.Page = 1;
            var roleList = AppConfigRegionSource.GetRoles().Where(x => x.Id == 1 || x.Id == 4 || x.Id == 5).Select(x => x.FriendlyName).ToArray();
            var countryList = userList.Select(x => x.Country).Distinct().ToArray();

            model.RoleList = new List<SelectListItem>();
            foreach (var role in roleList)
            {
                model.RoleList.Add(new SelectListItem { Text = role, Value = role });
            }

            model.CountryList = new List<SelectListItem>();
            foreach (var country in countryList)
            {
                model.CountryList.Add(new SelectListItem { Text = country, Value = country });
            }

            model.Alphabets = new char[] { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z' };

            return this.PartialView("UserSearchPartial", model);
        }

        public PartialViewResult SearchUsers(UserSearchViewModel model)
        {
            SearchCriteria criteria = new SearchCriteria();
            if (!string.IsNullOrEmpty(model.SelectedAlphabets[0]))
            {
                criteria.NameStartsWith = model.SelectedAlphabets[0].Split(',');
            }

            if (model.ApprovedSelected)
            {
                criteria.RequestStatus = (int)RequestStatus.Approved;
            }
            else if (model.RejectedSelected)
            {
                criteria.RequestStatus = (int)RequestStatus.Reject;
            }

            criteria.SelectedRole = model.SelectedCity;
            criteria.SelectedCountry = model.SelectedCountry;

            IEnumerable<IntialUserInfo> userList = this.adminManager.GetIntialUserList(criteria);
            userList = userList.OrderBy(x => x.UserName);

            if (model.Page < 1)
            {
                model.Page = 1;
            }

            var pagedUserlist = userList.Skip((model.Page - 1) * PageSize).Take(PageSize);
            ViewBag.rowCount = userList.Count();
            ViewBag.pageIndex = model.Page - 1;

            return this.PartialView("UsersPartial", pagedUserlist);
        }

        public PartialViewResult GetAllUsersSummary()
        {
            IEnumerable<UserInfo> users = this.adminManager.GetAllUsersInfo();

            UserSummaryViewModel viewModel = new UserSummaryViewModel();
            viewModel.UsersCount = users.Count();

            foreach (var user in users)
            {
                if (user.SuperAdmin)
                {
                    viewModel.PortalAdminCount++;
                }
                else
                {
                    var roles = user.RolesInfo;

                    if (Convert.ToInt16(roles["fcc"]) == Convert.ToInt16(roles["ofcom"]))
                    {
                        this.CountRoles(roles["fcc"].ToString(), ref viewModel);
                    }
                    else
                    {
                        this.CountRoles(roles["fcc"].ToString(), ref viewModel);
                        this.CountRoles(roles["ofcom"].ToString(), ref viewModel);
                    }
                }
            }

            viewModel.Countries = users.GroupBy(x => x.Country).Select(x => new
            {
                country = x.Key,
                count = x.Count()
            }).OrderByDescending(x => x.count).Select(x => x.country).Take(5).ToArray();

            viewModel.Cities = users.GroupBy(x => x.City).Select(x => new
            {
                city = x.Key,
                count = x.Count()
            }).OrderByDescending(x => x.count).Select(x => x.city).Take(5).ToArray();

            IEnumerable<AccessRequest> elevationRequests = this.adminManager.GetAllAccessRequests();
            viewModel.RequestsCount = elevationRequests.Count();

            return this.PartialView("SummaryPartial", viewModel);
        }        

        public PartialViewResult GetAllRequestsInfo()
        {
            IEnumerable<AccessRequest> requests = this.adminManager.GetAllAccessRequests();
            UserPrincipal userPrincipal = (UserPrincipal)User;

            Parallel.ForEach(
                requests, 
                request =>
                {
                    request.UserName = userPrincipal.UserManager.GetUserProfileFromUserId(request.UserId).UserName;
                });

            return this.PartialView("RequestsPartial", requests);
        }

        public JsonResult UpdateRequest(string userId, string regulatory, string remarks, bool isAccepted)
        {
            UserPrincipal user = (UserPrincipal)User;
            var requestedUser = user.UserManager.GetUserProfileFromUserId(userId);

            AccessRequest request = new AccessRequest();
            request.UserId = userId;
            request.RequestStatus = isAccepted == true ? (int)RequestStatus.Approved : (int)RequestStatus.Reject;
            request.Remarks = remarks.Trim().Replace('\n', ' ');
            request.Regulatory = regulatory;
            request.ApprovedUser = user.UserName;

            var result = this.adminManager.SaveAccessElevationRequest(request);

            if (result)
            {
                this.UserManagementAuditor.UserId = userId;
                this.UserManagementAuditor.TransactionId = this.UserManagementLogger.TransactionId;

                if (isAccepted)
                {
                    this.UserManagementAuditor.Audit(AuditId.RequestAccessElevation, AuditStatus.Success, default(int), "Access elevation request by " + requestedUser.UserName + " is approved by " + user.UserName);
                    this.UserManagementLogger.Log(TraceEventType.Information, LoggingMessageId.PortalUserAccessLevelElevationRequestApproved, requestedUser.UserName + " is approved by " + user.UserName);
                }
                else
                {
                    this.UserManagementAuditor.Audit(AuditId.RequestAccessElevation, AuditStatus.Success, default(int), "Access elevation request by " + requestedUser.UserName + " is rejected by " + user.UserName);
                    this.UserManagementLogger.Log(TraceEventType.Information, LoggingMessageId.PortalUserAccessLevelElevationRequestApproved, requestedUser.UserName + " is rejected by " + user.UserName);
                }

                return this.Json("Updated successfully");
            }

            this.UserManagementLogger.Log(TraceEventType.Error, LoggingMessageId.PortalUserAccessLevelElevationRequest, "Access elevation request updation failed");
            return this.Json("Updation failed");
        }

        public JsonResult GetUserInfo(string userId)
        {
            UserPrincipal userPrincipal = (UserPrincipal)User;
            UserDetails userDetails = userPrincipal.UserManager.GetUserAndAccessDetailsByUserId(userId);

            UserProfileModel profileModel = new UserProfileModel();
            if (userDetails != null)
            {
                profileModel.UserId = userDetails.UserInfo.RowKey;
                profileModel.FirstName = userDetails.UserInfo.FirstName;
                profileModel.LastName = userDetails.UserInfo.LastName;
                profileModel.PreferredEmail = userDetails.UserInfo.PreferredEmail;
                profileModel.PhoneCountryCode = userDetails.UserInfo.PhoneCountryCode;
                profileModel.Phone = userDetails.UserInfo.Phone;
                profileModel.Address1 = userDetails.UserInfo.Address1;
                profileModel.Address2 = userDetails.UserInfo.Address2;

src/Portal/Views/UserManagement/Index.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@section tabs
{
    <nav class="tab">
        <ul>
            <li class="summary">
                <input type="radio" class="hide" id="summaryTab" name="tabNav" checked="checked" />
                <label for="summaryTab">Summary</label>
            </li>
            <li class="access-request">
                <input type="radio" class="hide" id="accReq" name="tabNav" />
                <label for="accReq">Requests in Queue</label>
            </li>
            <li class="user-detail">
                <input type="radio" class="hide" id="users" name="tabNav" />
                <label for="users">User List</label>
            </li>
        </ul>
    </nav>
}

@section left
{
    <section class="noBorder">
        <div class="title">
            <h2>
                Manage Users
            </h2>
        </div>
    </section>
}

@section right
{
    <div id="summary">
        @{ Html.RenderAction("GetAllUsersSummary");}
    </div>
    <div id="userInfo" class="hide">
        @{ Html.RenderAction("LoadUserInfo");}
    </div>
    <div id="requests" class="hide">
        @using (Ajax.BeginForm("GetAllRequestsInfo", "UserManagement", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "requestsList", InsertionMode = InsertionMode.Replace,OnComplete = "OnSuccess" }))
        {
            <div id="requestsList">
                @Html.Action("GetAllRequestsInfo")
            </div>
        }
    </div>
}
@section Preloader{
    <div id="preloader" class="preloader"></div>
}

@section scripts{
    <script type="text/javascript" src="~/Scripts/Common.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        $("#wrapper").addClass("inner");
        //$("#right-pane").addClass("tabbedContainer");

        $("#users").click(function () {
            hideAll();
            $("#userInfo").removeClass("hide");
        });

        $("#accReq").click(function () {
            hideAll();
            $("#requests").removeClass("hide");
        });

        //$("#blockChannel").click(function () {
        //    hideAll();
        //    $("#channel").removeClass("hide");
        //});

        //$("#blockDevice").click(function () {
        //    hideAll();
        //    $("#device").removeClass("hide");
        //});

        $("#summaryTab").click(function () {
            hideAll();
            $("#summary").removeClass("hide");
        });

        function hideAll() {
            if (!$("#summary").hasClass("hide")) {
                $("#summary").addClass("hide");
            }
            if (!$("#userInfo").hasClass("hide")) {
                $("#userInfo").addClass("hide");
            }
            //if (!$("#channel").hasClass("hide")) {
            //    $("#channel").addClass("hide");
            //}
            if (!$("#requests").hasClass("hide")) {
                $("#requests").addClass("hide");
            }
            //if (!$("#device").hasClass("hide")) {
            //    $("#device").addClass("hide");
            //}
        };

        function OnSuccess() {
            $('.preloader').hide();
        };

        $(function () {
            $('#summary').perfectScrollbar({
                wheelSpeed: 20,
                wheelPropagation: true,
                minScrollbarLength: 20
            });

            $('#userDetails').perfectScrollbar({
                wheelSpeed: 20,
                wheelPropagation: true,
                minScrollbarLength: 20
            });

            $('#requests').perfectScrollbar({
                wheelSpeed: 20,
                wheelPropagation: true,
                minScrollbarLength: 20
            });
        });

    </script>
}

src/Portal/Views/UserManagement/RequestsPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model IEnumerable<Microsoft.WhiteSpaces.Common.AccessRequest>

<h2>Request in Queue</h2>

@if (Model.Count() > 0)
{
    WebGrid grid = new WebGrid(Model);

    @grid.GetHtml(
    columns: grid.Columns(
    grid.Column("UserName", "User Name"),
    grid.Column("Regulatory", "Regulatory"),
    grid.Column("CurrentRole", "Current Access Level"),
    grid.Column("RequestedRole", "Requested Access Level"),
    grid.Column("Justification", "Justification"),
    grid.Column("TimeUpdated", "Request Date"),
    grid.Column("", "",
    @<text>
        <a data-id="@item.UserId" data-regulatory="@item.Regulatory" class="accept-item">Accept</a>
        <a data-id="@item.UserId" data-regulatory="@item.Regulatory" class="deny-item error">Reject</a>
    </text>)))
}
else
{
    <label>No records found</label>
}

<input type="submit" class="hide" id="btnReload" />

<div id="dvRemarks" class="hide">
    <label>Remarks</label>
    <textarea rows="4" cols="50" id="txtRemarks"></textarea>
    <button id="btnOk">Ok</button>
    <button id="btnCancelRemarks">Cancel</button>
</div>


<script type="text/javascript">

    var rejectUserId = "";
    var authority = "";

    $(function () {
        $('.accept-item').on('click', function (e) {
            $('.preloader').show();
            var self = this;
            var userId = $(this).data('id');
            var regulatory = $(this).data('regulatory');
            var isAccepted = true;
            var remarks = "";
            ServerManager.AjaxRequest(
            {
                url: "/UserManagement/UpdateRequest",
                dataType: "JSON",
                type: "POST",
                data: { "userId": userId, "regulatory": regulatory, "isAccepted": isAccepted, "remarks": remarks },
                success: function (result) {
                    if (result.error) {
                        ServerManager.handleError(result, null);
                    }
                    $("#btnReload").click();
                },
                error: function (result) { }
            });
        });
        $('.deny-item').on('click', function (e) {
            var self = this;
            rejectUserId = $(this).data('id');
            authority = $(this).data('regulatory');

            $("#txtRemarks").focus();
            $("#dvRemarks").toggleClass("hide");
        });

        $('#btnCancelRemarks').on('click', function (e) {
            $("#dvRemarks").toggleClass("hide");
        });

        $("#btnOk").on('click', function (e) {
            $('.preloader').show();
            var isAccepted = false;
            var userId = rejectUserId;
            var remarks = $("#txtRemarks").val();
            var regulatory = authority;

            ServerManager.AjaxRequest(
            {
                url: "/UserManagement/UpdateRequest",
                dataType: "JSON",
                type: "POST",
                data: { "userId": userId, "regulatory": regulatory, "isAccepted": isAccepted, "remarks": remarks },
                success: function (result) {
                    $("#btnReload").click();
                },
                error: function (result) {}
            });
            $("#dvRemarks").toggleClass("hide");
        });
    });



</script>

src/Portal/Views/UserManagement/SummaryPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model Microsoft.WhiteSpaces.Portal.UserSummaryViewModel

<section class="info">
    <h2>Users Summary</h2>
    <ul>
        <li class="group-user">
            <label>Total User Count</label>
            <div class="input">
                <span>@Model.UsersCount</span>
            </div>
        </li>        
        <li class="pending">
            <label>Access Elevation Requests Count</label>
            <div class="input">
                <span>@Model.RequestsCount</span>
            </div>
        </li>        
    </ul>
</section>
<section class="info">
    <h2>DemoGraphics Summary</h2>
    <div class="col a">
        <h4>By City</h4>
        <ul>
            @foreach (string city in Model.Cities)
            {
                <li class="location">
                    <div class="input">
                        <span>@city</span>
                    </div>
                </li>
            }

        </ul>
    </div>
    <div class="col b">
        <h4>By Country</h4>
        <ul>
            @foreach (string country in Model.Countries)
            {
                <li class="location">
                    <div class="input">
                        <span>@country</span>
                    </div>
                </li>

            }
        </ul>
    </div>
</section>
<section class="info">
    <h2>Access Roles</h2>
    <ul>
        <li class="group-user">
            <label>Portal Users Count</label>
            <div class="input">
                <span>@Model.PortalUserCount</span>
            </div>
        </li>
        <li class="group-user">
            <label>Region Administrators Count</label>
            <div class="input">
                <span>@Model.RegionAdminCount</span>
            </div>
        </li>
        <li class="group-user">
            <label>Portal Administrators Count</label>
            <div class="input">
                <span>@Model.PortalAdminCount</span>
            </div>
        </li>
    </ul>
</section>

src/Portal/Views/UserManagement/UserSearchPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model Microsoft.WhiteSpaces.Portal.UserSearchViewModel
@using (Ajax.BeginForm("SearchUsers", "UserManagement", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "userDetails" }))
{
    <div id="dvList">
        <div class="filter">
            <div class="row">
                <ul id="radioFilter">
                    <li>                       
                        <input type="radio" name="filter" id="All" checked="checked" onchange="allChecked(this)" />
                        <label class="inline" for="All">All</label>
                    </li>
                    <li>
                        <input type="radio" name="filter" id="Approved" onchange="approvedChecked(this)" />
                        <label class="inline" for="Approved">Approved</label>
                    </li>
                    <li>
                        <input type="radio" name="filter" id="Rejected" onchange="rejectedChecked(this)" />
                        <label class="inline" for="Rejected">Rejected</label>
                    </li>
                </ul>
            </div>
            <div class="row">
                @Html.DropDownListFor(x => x.SelectedCity, @Model.RoleList, "Select Role")
                @Html.DropDownListFor(x => x.SelectedCountry, @Model.CountryList, "Select Country")
            </div>
            <div class="row">
                <div class="channel-list channel-num">
                    <ul id="Alphabets">
                        @foreach (char alpha in @Model.Alphabets)
                        {
                            <li>
                                @{var id = "chk" + alpha;}
                                <input type="checkbox" id="@id" class="hide" value="@alpha" />
                                <label for="@id">@alpha</label>
                            </li>
                        }
                    </ul>

                </div>
            </div>
            <div class="row clear noFollow">
                <button type="submit" role="button" class="filter right" id="findIncumbents" title="Find" onclick="beforeSubmit()">Filter It</button>
            </div>
        </div>
        <div id="userDetails">
            @Html.Partial("UsersPartial", @Model.UserList)
        </div>
        @Html.HiddenFor(x => x.SelectedAlphabets, new { @id = "alphabet" })
        @Html.HiddenFor(x => x.AllSelected, new { @id = "all" })
        @Html.HiddenFor(x => x.ApprovedSelected, new { @id = "approved" })
        @Html.HiddenFor(x => x.RejectedSelected, new { @id = "rejected" })
        @Html.HiddenFor(x => x.Page, new { @id = "page"})       
        <input type="hidden" value="false" id="isPaging"/>
    </div>
}

<div id="details" class="hide">
    <div class="title">
        <a href="" class="back icon" id="btnBack"></a>
        <h2>User Details</h2>
    </div>
    <section class="info">
        <div id="Profile">
            <ul>
                <li class="info name">
                    <label>First Name</label>
                    <div class="input" id="FirstName"></div>

                </li>

                <li class="info name">
                    <label>Last Name</label>
                    <div class="input" id="LastName"></div>
                </li>

                <li class="info country">
                    <label>Phone</label>
                    <div class="input" id="Phone"></div>
                </li>

                <li class="info email">
                    <label>Preferred Email</label>
                    <div class="input" id="PreferredEmail"></div>
                </li>

                <li class="info email">
                    <label>Account Email</label>
                    <div class="input" id="PreferredEmail"></div>
                </li>
            </ul>
        </div>
        <h2>Address</h2>
        <ul>
            <li class="info home">
                <label>Address1</label>
                <div class="input" id="Address1"></div>
            </li>

            <li class="info home">
                <label>Address2</label>
                <div class="input" id="Address2"></div>
            </li>

            <li class="info location">
                <label>City</label>
                <div class="input" id="City"></div>
            </li>

            <li class="info location">
                <label>State</label>
                <div class="input" id="State"></div>
            </li>

            <li class="info zip">
                <label>ZipCode</label>
                <div class="input" id="ZipCode"></div>
            </li>

            <li class="info location">
                <label>Country</label>
                <div class="input" id="Country"></div>
            </li>
            <li class="info country">
                <label>Time Zone</label>
                <div class="input" id="TimeZone"></div>
            </li>
        </ul>

        <div id="dvRequests" class="hide">
            <h2>Elevation Requests</h2>
            <table id="elevationRequests">
                <thead>
                    <tr>
                        <th>Regulatory</th>
                        <th>RequestedAccessLevel</th>
                        <th>Justification</th>
                        <th>RequestStatus</th>
                        <th>ApprovedUser</th>
                        <th>Remarks</th>
                        <th>TimeUpdated</th>
                    </tr>
                <tbody></tbody>
            </table>
        </div>

        <div id="dvRoles">
            <h2>Access Levels</h2>
            <table id="accessLevels">
                <thead>
                    <tr>
                        <th>Authority</th>
                        <th>Access Level</th>
                    </tr>
                <tbody></tbody>
            </table>

            <div class="end-stripe">
                <button id="btnEdit" type="button" title="Edit Profile" role="button" class="edit">Edit Access Levels</button>
            </div>
        </div>

        <div id="dvEditRoles" class="hide">
            <h2>Access Levels</h2>
            <table id="editAccessLevels">
                <thead>
                    <tr>
                        <th>Authority</th>
                        <th>Access Level</th>
                    </tr>
                <tbody></tbody>
            </table>

            <div class="end-stripe">
                <button id="btnUpdate" type="button" title="Update" class="submit" value="Update">Update</button>
                <button id="btnCancel" type="button" title="Cancel" class="cancel" value="Cancel">Cancel</button>
            </div>
        </div>

        <input type="hidden" id="userId" />
    </section>
</div>




<script type="text/javascript" src="~/Scripts/UserManagement.js"></script>
<script type="text/javascript">
    function assignAlpha(value) {
        var list = $("#alphabet").val() + "," + value;
        $("#alphabet").val(list);
    };

    function allChecked(obj) {
        if (obj.checked == true) {
            $("#all").val(true);
            $("#approved").val(false);
            $("#rejected").val(false);
        }
    }

    function approvedChecked(obj) {
        if (obj.checked == true) {
            $("#approved").val(true);
            $("#all").val(false);
            $("#rejected").val(false);
        }
    }

    function rejectedChecked(obj) {
        if (obj.checked == true) {
            $("#rejected").val(true);
            $("#all").val(false);
            $("#approved").val(false);
        }
    }

    function beforeSubmit() {        
        if ($("#isPaging").val() == "true")
        {            
            $("#isPaging").val("false")
        }
        else
        {
            $("#page").val(1);
        }

        selectedAlphabets = [];
        $("#alphabet").val("");

        $('#Alphabets input:checked').each(function () {
            selectedAlphabets.push($(this).val());
        });

        if (selectedAlphabets.length > 0) {
            $("#alphabet").val(selectedAlphabets);
        }

        var radio = $('input[name=filter]:checked', '#radioFilter').val();       
        return true;
    }
</script>

src/Portal/Views/UserManagement/UsersPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model IEnumerable<Microsoft.WhiteSpaces.Common.IntialUserInfo>

@if (Model.Count() > 0)
{
    WebGrid grid = new WebGrid(rowsPerPage: 10);
    grid.Bind(Model, autoSortAndPage: false, rowCount: ViewBag.rowCount);
    grid.Pager(WebGridPagerModes.All);
    grid.PageIndex = ViewBag.pageIndex;

    @grid.GetHtml(htmlAttributes: new { id = "intialList" },
    mode: WebGridPagerModes.All,
    firstText: "<< First",
    previousText: "< Prev",
    nextText: "Next >",
    lastText: "Last >>",
    columns: grid.Columns(
    grid.Column("", "User Name", @<text><a data-id="@item.Id" class="view-item">@item.UserName</a></text>),
    grid.Column("PrefferedEmail", "Preferred Email",canSort:false),
    grid.Column("Regulatory", "Regulatory", canSort: false),
    grid.Column("Role", "Role", canSort: false),
    grid.Column("RequestStatus", "RequestStatus", canSort: false),
    grid.Column("DateRegistered", "DateRegistered", canSort: false),
    grid.Column("Country", "Country", canSort: false)))
    if (Convert.ToInt16(ViewBag.rowCount) > 10)
    {
        <div class="total-count">Total Records: @ViewBag.rowCount</div>
    }
}
else
{
    <label>No records found</label>
}


<script type="text/javascript">
    $(function () {
        $("#userDetails a").on('click', function (event) {
            if (this.className == "view-item") {
                var userManagement = new UserManagement();
                userManagement.getUserDetails($(this).data('id'));
            }
            else {
                event.preventDefault();
                var href = $(this).attr("href");
                var page = href.substring(href.indexOf('=') + 1, href.length);
                $("#page").val(page);
                $("#isPaging").val("true");
                $("#findIncumbents").click();
            }

        });
    })
</script>