src/Portal/Controllers/PublicDataController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.WhiteSpaces.Portal.Controllers
{
    using System;
    using System.Text;
    using System.Web.Mvc;
    using Microsoft.WhiteSpaces.BusinessManager;
    using Microsoft.WhiteSpaces.Common;

    [AllowAnonymous]
    public class PublicDataController : Controller
    {
        private readonly IPublicDataManager dataManager;
        private readonly IRegionSource regionSource;

        public PublicDataController(IPublicDataManager dataManager, IRegionSource regionSource)
        {
            if (dataManager == null)
            {
                throw new ArgumentNullException("dataManager");
            }

            if (regionSource == null)
            {
                throw new ArgumentException("regionSource");
            }

            this.dataManager = dataManager;
            this.regionSource = regionSource;
        }

        public ActionResult Index()
        {
            this.ViewData["availableRegions"] = this.regionSource.GetAvailableRegions();

            return this.View();
        }

        public FileResult GetPublicDataWithEvents(string entityType)
        {
            var csvString = this.dataManager.GetPublicDataWithEvents(entityType);
            var byteArray = Encoding.ASCII.GetBytes(csvString);

            string fileName = string.Empty;
            switch (entityType)
            {
                case "MVPD": fileName = "cablevideomvpd.csv";
                    break;
                case "TBAS": fileName = "temporarybaslinks.csv";
                    break;
                case "LPAux": fileName = "lowpoweraux.csv";
                    break;
                case "FIXED_TVBD": fileName = "fixedtvbd.csv";
                    break;
                default: fileName = entityType.ToLower() + ".csv";
                    break;
            }

            return this.File(byteArray, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public FileResult GetPublicData(string entityType)
        {
            var csvString = this.dataManager.GetPublicData(entityType);
            var byteArray = Encoding.ASCII.GetBytes(csvString);

            string fileName = string.Empty;
            switch (entityType)
            {
                case "TV_US": fileName = "usstations.csv";
                    break;
                case "TVCA_MX": fileName = "canadamexicostations.csv";
                    break;
                case "TV_TRANSLATOR": fileName = "tvtranslators.csv";
                    break;
                case "BAS": fileName = "baslinks.csv";
                    break;
                case "PLCMRS": fileName = "plmrs-cmrs.csv";
                    break;
                default: fileName = entityType.ToLower() + ".csv";
                    break;
            }

            return this.File(byteArray, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public FileResult GetAuthorizedDeviceModels()
        {
            var csvString = this.dataManager.GetAuthorizedDeviceModels();
            var byteArray = Encoding.ASCII.GetBytes(csvString);

            return this.File(byteArray, System.Net.Mime.MediaTypeNames.Application.Octet, "FCC_WhiteSpace_Authorization.csv");
        }

        public FileResult GetUlsCallSigns()
        {
            var csvString = this.dataManager.GetUlsCallSigns();
            var byteArray = Encoding.ASCII.GetBytes(csvString);

            return this.File(byteArray, System.Net.Mime.MediaTypeNames.Application.Octet, "ulscallsigns.csv");
        }

        public FileResult GetUlsFileNumbers()
        {
            var csvString = this.dataManager.GetUlsFileNumbers();
            var byteArray = Encoding.ASCII.GetBytes(csvString);

            return this.File(byteArray, System.Net.Mime.MediaTypeNames.Application.Octet, "ulsfilenumbers.csv");
        }
    }
}

src/Portal/Controllers/WSFinderController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.WhiteSpaces.Portal.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Device.Location;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Microsoft.Practices.Unity;
    using Microsoft.Whitespace.Common;
    using Microsoft.Whitespace.Entities;
    using Microsoft.WhiteSpaces.BusinessManager;
    using Microsoft.WhiteSpaces.Common;
    using Microsoft.WhiteSpaces.Common.Entities;
    using Microsoft.WhiteSpaces.Common.Enums;
    using Microsoft.WhiteSpaces.Common.UnitConvertor;
    using Microsoft.WhiteSpaces.Common.Utilities;
    using Microsoft.WhiteSpaces.Portal.Models;
    using INCU = Microsoft.WhiteSpaces.Common.Incumbent;

    [AllowAnonymous]
    public class WSFinderController : Controller
    {
        private const string RegionCode = "RegionCode";

        private readonly IWhitespacesManager whitespacesManager;
        private readonly IRegionSource regionSource;

        public WSFinderController(IWhitespacesManager whitespacesManager, IRegionSource regionSource)
        {
            if (whitespacesManager == null)
            {
                throw new ArgumentNullException("whitespacesManager");
            }

            if (regionSource == null)
            {
                throw new ArgumentNullException("regionSource");
            }

            this.whitespacesManager = whitespacesManager;
            this.regionSource = regionSource;
        }

        [Dependency]
        public IAuditor WhitespaceFinderAuditor { get; set; }

        [Dependency]
        public ILogger WhitespaceFinderLogger { get; set; }

        // GET: /WSFinder/
        public ActionResult Index()
        {
            this.ViewData["availableRegions"] = this.regionSource.GetAvailableRegions().Select(region => region.RegionInformation).ToList();

            return this.View();
        }

        public ViewResult GetWhitespacesFinderView(string regulatoryName)
        {
            Region currentRegion = this.regionSource.GetAvailableRegions()
                                                    .Where(region => string.Compare(regulatoryName, region.Regulatory.Name, StringComparison.OrdinalIgnoreCase) == 0)
                                                    .FirstOrDefault();

            this.ViewData["availableRegions"] = new List<RegionInfo> { currentRegion.RegionInformation };

            RegionWhitespaceDetails whitespaceDetails = this.GetRegionWhitespaceDetails(currentRegion.Regulatory.RegionCode, null);

            return this.View("RegionSpecificFinder", whitespaceDetails);
        }

        public PartialViewResult GetCountryRegionSpecificControls(RegionSearchParams model)
        {
            RegionWhitespaceDetails whitespaceDetails = this.GetRegionWhitespaceDetails(model.RegionCode, model.AntennaHeight);

            return this.PartialView("WhitespaceDetailsPartial", whitespaceDetails);
        }

        public PartialViewResult FindNearByIncumbents(RegionSearchParams model)
        {
            RegionWhitespaceDetails whitespaceDetails = this.GetRegionWhitespaceDetails(model, this.ModelState.IsValid);

            return this.PartialView("WhitespaceDetailsPartial", whitespaceDetails);
        }

        public JsonResult GetProtectedIncumbents(string incumbentType, string countryRegion, int channel)
        {
            Region region = this.regionSource.GetAvailableRegions().FirstOrDefault(country => string.Compare(country.RegionInformation.Name, countryRegion, StringComparison.OrdinalIgnoreCase) == 0);

            if (this.ModelState.IsValid && region != null)
            {
                List<int> channelList = new List<int>() { channel };
                List<INCU> incumbents = this.whitespacesManager.GetIncumbents(incumbentType, countryRegion, channelList);

                JsonResult jsonResult = this.Json(incumbents, JsonRequestBehavior.AllowGet);

                jsonResult.MaxJsonLength = int.MaxValue;

                return jsonResult;
            }

            return null;
        }

        public ActionResult GetIncumbents(RegionSearchParams searchParams, int[] channels)
        {
            List<INCU> incumbents = new List<INCU>();
            Region region = this.regionSource.GetAvailableRegions().FirstOrDefault(rgn => string.Compare(rgn.RegionInformation.Name, searchParams.CountryRegion, StringComparison.OrdinalIgnoreCase) == 0);

            if (region == null)
            {
                //// TODO: Logic to handle Invalid CountryRegion as argument.
            }

            incumbents = this.whitespacesManager.GetIncumbents(searchParams.IncumbentType, searchParams.Latitude, searchParams.Longitude, searchParams.CountryRegion, channels);

            // TODO: May be we need to have condition check below to make sure following filter logic executes only for FCC. 

            // [Temporary fix]: Commenting following search location based filtering, because for incumbent type such as "TV_US" is not return TransmitLocation,
            // which plays a major role in filtering the incumbents for the given search location.
            // incumbents = this.FilterIncumbentsByRegion(searchParams.Latitude, searchParams.Longitude, incumbents);
            incumbents = this.FilterIncumbentsByChannels(channels, incumbents);

            return this.Json(incumbents, JsonRequestBehavior.AllowGet);
        }

        private static IEnumerable<ProtectedDevice> FilterPortectedDevicesByChannel(IEnumerable<ProtectedDevice> protectedDevices, int channel)
        {
            if (protectedDevices != null)
            {
                protectedDevices = protectedDevices.Where(device => device.Channels.Contains(channel));
            }

            return protectedDevices;
        }

        /// <summary>
        /// Code to extract all the incumbents filtered by Channel Number across the country region.
        /// </summary>
        /// <param name="incumbents">list of incumbents</param>
        /// <param name="tvbdType">type of incumbents</param>
        private static void WriteIncumbentsToAFile(IEnumerable<INCU> incumbents, string tvbdType)
        {
            string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Incumbent.txt");
            FileStream stream = System.IO.File.OpenWrite(filePath);
            if (stream != null)
            {
                stream.Close();
                List<string> contents = incumbents.Select(incumbent =>
                {
                    bool contourAvailability = incumbent.ContourPoints != null && incumbent.ContourPoints.Any();

                    return string.Format(
                        "Incumbent Type: {0}{1} Channel No:{2}, Contours Availability Status:{3} {4} Latitude:{5}, Longitude:{6}{7} -----------^^^^^",
                        incumbent.Type.ToString(),
                        Environment.NewLine,
                        incumbent.Channel,
                        contourAvailability,
                        Environment.NewLine,
                        incumbent.TransmitLocation.Latitude,
                        incumbent.TransmitLocation.Longitude,
                        Environment.NewLine);
                }).ToList();

                contents.Insert(0, string.Format("TVBD Type: {0}{1}^^^^^^^---------------", tvbdType, Environment.NewLine));

                System.IO.File.AppendAllLines(filePath, contents);
            }
        }

        private RegionWhitespaceDetails GetRegionWhitespaceDetails(string regionCode, double? antennaHeight)
        {
            IEnumerable<Region> supportedCountries = this.regionSource.GetAvailableRegions();
            Region region = supportedCountries.FirstOrDefault(country => string.Compare(country.Regulatory.RegionCode, regionCode, StringComparison.OrdinalIgnoreCase) == 0);

            RegionSearchParams defaultSearchParams = new RegionSearchParams
            {
                CountryRegion = region != null ? region.RegionInformation.Name : string.Empty
            };

            if (region != null)
            {
                defaultSearchParams.RegionCode = region.Regulatory.RegionCode;
                defaultSearchParams.Latitude = region.RegionInformation.Latitude;
                defaultSearchParams.Longitude = region.RegionInformation.Longitude;
                defaultSearchParams.IncumbentType = region.Regulatory.SupportedDeviceTypes.FirstOrDefault().Type;
                defaultSearchParams.AntennaHeight = antennaHeight;
            }

            return this.GetRegionWhitespaceDetails(defaultSearchParams, false);
        }

        private RegionWhitespaceDetails GetRegionWhitespaceDetails(RegionSearchParams searchParams, bool getChannelInfoList)
        {
            Region region = this.regionSource.GetAvailableRegions().FirstOrDefault(rgn => string.Compare(rgn.Regulatory.RegionCode, searchParams.RegionCode, StringComparison.OrdinalIgnoreCase) == 0);

            RegionWhitespaceDetails whitespaceDetails = new RegionWhitespaceDetails
            {
                AntennaHeight = searchParams.AntennaHeight,
                Location = searchParams.Location,
                EnableProtectedAreas = region != null ? region.Regulatory.AllowAccessToProtedtedArea : false
            };

            if (region != null)
            {
                whitespaceDetails.StartChannelNo = region.Regulatory.WSChannelsInfo.StartChannel;
                whitespaceDetails.EndChannelNo = region.Regulatory.WSChannelsInfo.EndChannel;

                if (region.Regulatory.SupportedDeviceTypes != null)
                {
                    whitespaceDetails.DeviceTypes = region.Regulatory.SupportedDeviceTypes.ToList();

src/Portal/Views/Shared/FooterPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


<footer>
    <div class="container">
        <nav>
            @* TODO: Update all the footer links to right uri. *@
            <ul>
                @*<li>
                    @Html.ActionLink("About","About","Home")
                </li>*@
                <li>                    
                    @Html.ActionLink("Privacy", "Privacy", "Home")
                </li>
                <li>
                    @Html.ActionLink("Terms of Use", "TermsOfUse", "Home")
                </li>
                <li>
                    @Html.ActionLink("Contact Us", "ContactUs", "Home")
                </li>
            </ul>
        </nav>
        <div class="copyright">© 2014 Microsoft</div>
    </div>
</footer>

src/Portal/Views/Shared/HelpControlPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model Microsoft.WhiteSpaces.Portal.Models.HelpControl
<button class="icon info noBg" name="@Model.DomElementId" title="Know More">ℹ</button>
<div id="notification" style="display:none">
    @Html.Partial("NoficationBolloonControlPartial", @Model)
</div>

src/Portal/Views/Shared/InfoboxPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model Microsoft.WhiteSpaces.Common.Entities.Region

@{
    System.Text.StringBuilder deviceTypesLabel = new System.Text.StringBuilder();

    Microsoft.WhiteSpaces.Common.Entities.DeviceType[] deviceTypes = @Model.Regulatory.SupportedDeviceTypes.ToArray();
}

@for (int i = 0; i < deviceTypes.Length; i++)
{
    deviceTypesLabel.Append(deviceTypes[i].FriendlyName);

    if (i != deviceTypes.Length - 1)
    {
        deviceTypesLabel.Append(", ");
    }
}

<div class="infobox">
    <div class="infobox-body">
        <div class="title">
            <h2>@Model.RegionInformation.Name</h2>
            <nav class="options">
                <ul>
                    <li>
                        @Html.ActionLink("Find White Spaces", "GetWhitespacesFinderView", "WSFinder", new { regulatoryName = @Model.Regulatory.Name }, new { role = "link", title = "Find Whitespaces" })</li>

                        @if (Model.Regulatory.SupportedFeatures.Contains("download"))
                        {
                            <li><a href="@Url.Action("Index", "PublicData")" title="Download Data">Download Data</a></li>
                        }

                        @if (Model.Regulatory.SupportedFeatures.Contains("register incumbents"))
                        {
                            <li>
                                <a href="@Url.Action("Index", "RegisterMVPD")" title="Register Incumbents">Register Incumbents</a>
                            </li>
                        }
                </ul>
            </nav>

        </div>
        <section>
            <h4>@Model.Regulatory.Name</h4>
            <ul>
                <li>
                    <label>Device Types</label>
                    <span>
                        @deviceTypesLabel.ToString()
                    </span>
                </li>
                <li>
                    <label>Operating Channels</label>
                    <span>@Model.Regulatory.WSChannelsInfo.StartChannel - @Model.Regulatory.WSChannelsInfo.EndChannel</span>
                </li>
                <li>
                    <label>Channel Bandwidth</label>
                    <span>@Model.Regulatory.WSChannelsInfo.ChannelBandwidth MHz</span>
                </li>
                <li>
                    <label>Propagation Model</label>
                    <span>@Model.Regulatory.WSChannelsInfo.PropagationModel</span>
                </li>
            </ul>
        </section>
    </div>
    <div class="infobox-stalk"></div>
</div>

src/Portal/Views/Shared/LpauxRegistrations.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@model IEnumerable<Microsoft.Whitespace.Entities.LPAuxRegistration>

@if (Model.Count() > 0)
{
    WebGrid lpAuxGrid = new WebGrid(rowsPerPage: 5);
    lpAuxGrid.Bind(Model, autoSortAndPage: false, rowCount: ViewBag.lpauxRowCount);
    lpAuxGrid.Pager(WebGridPagerModes.All);

    @lpAuxGrid.GetHtml(htmlAttributes: new { id = "lpAuxGrid" },
     mode: WebGridPagerModes.All,
     firstText: "<< First",
     previousText: "< Prev",
     nextText: "Next >",
     lastText: "Last >>",
    columns: lpAuxGrid.Columns(
             lpAuxGrid.Column("", "ULS FileNumber", @<text> @item.ULSFileNumber </text>),
             lpAuxGrid.Column("", "Licensed", @<text> @item.Licensed </text>),
             lpAuxGrid.Column("", "Venue", @<text> @item.VenueName </text>),
             lpAuxGrid.Column("", "Location", @<text> @item.Latitude , @item.Longitude </text>),
 lpAuxGrid.Column("", "Registration Date", @<text> @item.Disposition.RegDate </text>),
          lpAuxGrid.Column("", "", @<text>  <a data-pk="@item.PartitionKey" data-rk="@item.RowKey" data-type="LpAux" data-etag="@item.ETag" class="del-lpaux delete icon">Delete</a> </text>)
                  ))
    if (Convert.ToInt16(ViewBag.lpauxRowCount) > 5)
    {
        <div class="total-count">Total Records: @ViewBag.lpauxRowCount</div>
    }
}
else
{
    <label>No records found</label>
}

src/Portal/Views/Shared/MapPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


<div id="mapDiv" class="map-area"></div>

<script charset="UTF-8" type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>
<script type="text/javascript" src="~/Scripts/bingmap.js"></script>
<script type="text/javascript" src="~/Scripts/Common.js"></script>
<script type="text/javascript">
    var credentials = @Html.Raw(Json.Encode(Microsoft.WhiteSpaces.Common.ConfigHelper.BingCredential));
    var mapControl = document.getElementById("mapDiv");
    var bingMap = new BingMap(credentials, mapControl);

    $(window).unload(function () {
        bingMap.UnloadMap();
    })
</script>

src/Portal/Views/Shared/_TabStripPartial.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@using Microsoft.WhiteSpaces.Portal;
@using Microsoft.Web.WebPages.OAuth;
@using Microsoft.WhiteSpaces.Portal.Models;

<nav class="tab-strip">
    <ul>
        <li class="home">
            @Html.ActionLink("Home", "Index", "Home")
            <span></span>
        </li>
        <li class="available-region">
            @Html.ActionLink("Available Regions", "GetAvailableRegions", "Home")
            <span></span>
        </li>
        <li class="finder">
            @Html.ActionLink("White Spaces Finder", "Index", "WSFinder")
            <span></span>
        </li>
        @*<li class="download-data">
            @Html.ActionLink("Download Data", "Index", "PublicData")
            <span></span>
        </li>*@

        @if (Request.IsAuthenticated)
        {
            <li class="profile">
                @Html.ActionLink("Profile", "Index", "Profile")
                <span></span>
            </li>

            UserPrincipal principal = (UserPrincipal)User;

            if (principal.IsSuperAdmin)
            {
                <li class="user-management">
                    @Html.ActionLink("Manage User", "Index", "UserManagement")
                    <span></span>
                </li>
            }
            @*<li class="register-incumbent">
                @Html.ActionLink("Register Incumbents", "Index", "RegisterMVPD")
                <span></span>
            </li>*@
            if (principal.IsSuperAdmin || principal.IsRegionAdmin)
            {
                <li class="manage-region">
                    @Html.ActionLink("Manage Region", "Index", "RegionManagement")
                    <span></span>
                </li>
            }
            <li class="feedback">
                @Html.ActionLink("Feedback", "Index", "Feedback")
                <span></span>
            </li>
            <li class="faq">
                @Html.ActionLink("FAQ", "FAQ", "Home")
                <span></span>
            </li>
            <li class="demo">
                @Html.ActionLink("How it works? Watch Demo", "HowItWorks", "Home", new { id="howItWorks", title = "How it works? Watch Demo" })
                <span></span>
            </li>
            <li class="signout">
                @using (Html.BeginRouteForm("Default", new { controller = "Account", action = "LogOff" }, FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()" role="link">SignOut</a>
                    <span></span>
                }
            </li>
        }
        else
        {
            <li class="feedback">
                @Html.ActionLink("Feedback", "Index", "Feedback")
                <span></span>
            </li>
            <li class="faq">
                @Html.ActionLink("FAQ", "FAQ", "Home")
                <span></span>
            </li>
            <li class="demo">
                @Html.ActionLink("How it works? Watch Demo", "HowItWorks", "Home", new { id="howItWorks", title = "How it works? Watch Demo" })
                <span></span>
            </li>
            <li class="signin">
                @using (Html.BeginRouteForm("Default", new { controller = "Account", action = "ExternalLogin" }, FormMethod.Post, new { returnUrl = ViewBag.ReturnUrl, id = "loginForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("provider", OAuthWebSecurity.RegisteredClientData.FirstOrDefault().AuthenticationClient.ProviderName)
                    <a href="javascript:document.getElementById('loginForm').submit()" role="link">Sign In</a>
                    <span></span>
                }
            </li>
        }
    </ul>
</nav>
<script type="text/javascript">
    
</script>

src/Portal/Views/Shared/_TabStripPartialRight.cshtml
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->


@using Microsoft.WhiteSpaces.Portal;
@using Microsoft.Web.WebPages.OAuth;
@using Microsoft.WhiteSpaces.Portal.Models;

<nav class="tab-strip right">
    <ul>
        <li class="home">
            @Html.ActionLink("Home", "Index", "Home")
            <span></span>
        </li>
        <li class="available-region">
            @Html.ActionLink("Available Regions", "GetAvailableRegions", "Home")
            <span></span>
        </li>
        <li class="finder">
            @Html.ActionLink("White Spaces Finder", "Index", "WSFinder")
            <span></span>
        </li>
        @*<li class="download-data">
            @Html.ActionLink("Download Data", "Index", "PublicData")
            <span></span>
        </li>*@

        @if (Request.IsAuthenticated)
        {
            <li class="profile">
                @Html.ActionLink("Profile", "Index", "Profile")
                <span></span>
            </li>

            UserPrincipal principal = (UserPrincipal)User;

            if (principal.IsSuperAdmin)
            {
                <li class="user-management">
                    @Html.ActionLink("Manage User", "Index", "UserManagement")
                    <span></span>
                </li>
            }
            @*<li class="register-incumbent">
                @Html.ActionLink("Register Incumbents", "Index", "RegisterMVPD")
                <span></span>
            </li>*@
            if (principal.IsSuperAdmin || principal.IsRegionAdmin)
            {
                <li class="manage-region">
                    @Html.ActionLink("Manage Region", "Index", "RegionManagement")
                    <span></span>
                </li>
            }
            <li class="feedback">
                @Html.ActionLink("Feedback", "Index", "Feedback")
                <span></span>
            </li>
            <li class="faq">
                @Html.ActionLink("FAQ", "FAQ", "Home")
                <span></span>
            </li>
            <li class="demo">
                <a id="howItWorks" href="#" title="How it works? Watch Demo">How it works? Watch Demo</a>
            </li>
            <li class="signout">
                @using (Html.BeginRouteForm("Default", new { controller = "Account", action = "LogOff" }, FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()" role="link">SignOut</a>
                    <span></span>
                }
            </li>
        }
        else
        {
            <li class="feedback">
                @Html.ActionLink("Feedback", "Index", "Feedback")
                <span></span>
            </li>
            <li class="faq">
                @Html.ActionLink("FAQ", "FAQ", "Home")
                <span></span>
            </li>
            <li class="demo">
                <a id="howItWorks" href="#" title="How it works? Watch Demo">How it works? Watch Demo</a>
            </li>
            <li class="signin">
                @using (Html.BeginRouteForm("Default", new { controller = "Account", action = "ExternalLogin" }, FormMethod.Post, new { returnUrl = ViewBag.ReturnUrl, id = "loginForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("provider", OAuthWebSecurity.RegisteredClientData.FirstOrDefault().AuthenticationClient.ProviderName)
                    <a href="javascript:document.getElementById('loginForm').submit()" role="link">Sign In</a>
                    <span></span>
                }
            </li>
        }
    </ul>
</nav>
<script type="text/javascript">
    $(document).ready(function () {
        var constant = 533;
        
        var slideCount = $('.how-it-works ul li').length;
        var maxLeft = slideCount * constant;

        

        $('#howItWorks').click(function () {
            $('#howItWorksContainer').show();
            $('.how-it-works ul').css('margin-left', 0);
            $('#previousSlide').attr('disabled', true);
            constant = $('.how-it-works ul li').first().outerWidth() + parseInt($('.how-it-works ul li').first().css('margin-right'), 10);
        });

        $('#previousSlide').click(function () {
            var nextValue = parseInt($('.how-it-works ul').css('margin-left'), 10) + constant;
            if (nextValue < constant) {
                $('.how-it-works ul').css('margin-left', nextValue);
                $('#nextSlide').attr('disabled', false);
                $('#previousSlide').attr('disabled', true);
                setTimeout(function () {
                    $('#previousSlide').attr('disabled', false);
                }, 800)
            } else {
                $('#previousSlide').attr('disabled', true);
            }
        })

        $('#nextSlide').click(function () {
            var nextValue = parseInt($('.how-it-works ul').css('margin-left'), 10) - constant;
            if (Math.abs(nextValue) <= maxLeft) {
                $('.how-it-works ul').css('margin-left', nextValue);
                $('#previousSlide').attr('disabled', false);
                $('#nextSlide').attr('disabled', true);
                setTimeout(function () {
                    $('#nextSlide').attr('disabled', false);
                }, 800)
            } else {
                $('#nextSlide').attr('disabled', true);
            }
        })

        $('#closeHowItWorks').click(function () {
            $('#howItWorksContainer').hide();
        });

    });
</script>